# ---------------------------------------------------------------------
# Gufo HTTP: _fast typing
# ---------------------------------------------------------------------
# Copyright (C) 2024, Gufo Labs
# See LICENSE.md for details
# ---------------------------------------------------------------------

# Python modules
from typing import Iterable, Optional, Tuple

class HttpError(Exception): ...

class Headers(object):
    def __contains__(self: "Headers", k: str) -> bool: ...
    def __getitem__(self: "Headers", k: str) -> bytes: ...
    def get(
        self: "Headers", k: str, default: Optional[bytes]
    ) -> Optional[bytes]: ...
    def keys(self: "Headers") -> Iterable[str]: ...
    def values(self: "Headers") -> Iterable[bytes]: ...
    def items(self: "Headers") -> Iterable[Tuple[str, bytes]]: ...

class AsyncResponse(object):
    @property
    def status(self: "AsyncResponse") -> int: ...
    @property
    def headers(self: "AsyncResponse") -> Headers: ...
    async def read(self: "AsyncResponse") -> bytes: ...

class AsyncClient(object):
    def __init__(
        self: "AsyncClient", max_redirects: Optional[int]
    ) -> None: ...
    async def get(self: "AsyncClient", url: str) -> AsyncResponse: ...
